"use strict";
exports.__esModule = true;
var datasource_1 = require("./datasource");
var data = require("./data");
var db = data();
var myStaticData = new datasource_1.StaticDataSource();
var productlisting = myStaticData.getProducts();
var categoryListing = myStaticData.getCategories();
console.log(productlisting);
console.log(categoryListing);
